#!/usr/bin/env node

// see lib/app.js for info
var program = require('commander');

program
    .version('1.0.0')
    .option('-v, --verbose', 'enable verbose reporting')
    .option('-q, --quiet', 'hide all notifications')
    .parse(process.argv);

var config = {
        inFile: 'data.json',
        outFile: 'data-min.js',
        githubLastPushCutoffMonths: 48, // for now—need to tweak this later,
        errorCountThreshold: 10,
        program: program
    };

require('./lib/start.js').start(config);